apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mmdox11pk-go
  janus-idp.io/tekton: mmdox11pk-go
  backstage.io/kubernetes-id: mmdox11pk-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mmdox11pk-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
