apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mmdox11pk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mmdox11pk-go 
  name: mmdox11pk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mmdox11pk-go 
