apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mmdox11pk-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:737588b4243bc6a44ae2baf751fa4e0d8d741d56@sha256:b9e04cd6566a740ea7bda213b87f14ff4b183e53171ba24d50e3e10b89b020a4
          name: container-image
